# vim: nospell
language: generic
sudo: required
dist: trusty

matrix:
  include:
    - env: GHC=7.8.4 LLVM=3.4 CUDA=7.0-28
      compiler: "#GHC 7.8"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.8.4
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.4
            - libcudart4

    - env: GHC=7.10.3 LLVM=3.5 CUDA=7.0-28
      compiler: "#GHC 7.10"
      addons:
        apt:
          sources:
            - hvr-ghc
            # - llvm-toolchain-precise-3.5
            # - ubuntu-toolchain-r-test
          packages:
            - ghc-7.10.3
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.4
            - llvm-3.5
            - libcudart7.5

cache:
  directories:
    - $HOME/.stack

# cache:
#   directories:
#     - $HOME/.ghc
#     - $HOME/.cabal/bin
#     - $HOME/.cabal/lib
#     - $HOME/.cabal/share

before_install:
  - unset CC
  - export PATH=/opt/alex/3.1.4/bin:${PATH}
  - export PATH=/opt/happy/1.19.5/bin:${PATH}
  - export PATH=/opt/cabal/1.22/bin:${PATH}
  - export PATH=/opt/ghc/${GHC}/bin:${PATH}
  - export PATH=/usr/lib/llvm-${LLVM}/bin:${PATH}

  # Fetch stack
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | gunzip | tar -x
  - mv stack-*/stack $HOME/bin
  - ln -s stack-${GHC%.*}.yaml stack.yaml
  - travis_retry stack setup --no-terminal
  - |
      if [ ${GHC%.*} == 7.8 ]; then
        # required to install the 'cuda' package
        travis_retry sudo env PATH=$PATH stack setup --upgrade-cabal --allow-different-user --no-terminal
        # GCE architecture doesn't have enough space in /tmp to install stack
        # locally, so we need to install via apt and then --upgrade-cabal using
        # 'sudo'. This fixes the resulting permissions.
        sudo chown -R $USER:$USER $HOME/.stack
      fi
  - ls -la $HOME
  - ls -la $HOME/.stack
  - ls -la $HOME/.stack/indices
  - ls -la $HOME/.stack/indices/*
  - ls -la $HOME/.stack/indices/*/*

  # Install CUDA
  # - source .travis/install-cuda-trusty.sh

install:
  - which -a stack
  - which -a cabal
  - which -a ghc
  - which -a opt
  - which -a llc
  - which -a alex
  - which -a happy
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - cabal --version
  - alex --version
  - happy --version
  - opt --version; true
  - llc --version; true
  - nvcc --version

  # - travis_retry .travis/install_dependencies.sh

script:
  - stack build --no-terminal
  - stack exec travis-test

