language: haskell
addons:
  apt:
    sources:
      - hvr-ghc
      - llvm-toolchain-precise
    packages:
      - happy-1.19.5
      - alex-3.1.4
      - cabal-install-1.22
      - ghc-7.10.1
      - clang-3.5

env:
    - GHC=7.8.4
    - GHC=7.10.1

before_install:
    - export PATH=/opt/alex/3.1.4/bin:${PATH}
    - export PATH=/opt/happy/1.19.5/bin:${PATH}
    - export PATH=/opt/cabal/1.22/bin:${PATH}
    - export PATH=/usr/local/ghc/${GHC}/bin:${PATH}
    - export PATH=/usr/local/clang-3.5/bin:${PATH}

install:
    - echo ${PATH}
    - which -a cabal
    - which -a ghc
    - which -a opt
    - which -a llc
    - which -a alex
    - which -a happy
    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - cabal --version
    - alex --version
    - happy --version
    - opt --version; true
    - llc --version; true

script:
    - cabal install
    - travis-test

